INSERT INTO tb_category (name, created_At) VALUES ('Entradas', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Massas', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Risotos', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bebidas', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sobremesa', NOW());

INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Antepastos', 32.5, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Porções de sardella, berinjela, caponata, abobrinha e pasta da casa companhados de pao caseiro italiano.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/antepasto.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Bruschetta', 29.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Bruschetta al crudo, servida com mussarela de búfala, tomate, rúcula e presunto cru.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/bruschettas.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Burrata', 39.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Burrata ao molho pesto com tomate-cereja confitado, minirrúcula e torradas.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/burrata.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Macarrão Espaguete', 45.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Macarrão fresco espaguete com molho especial e tempero da casa.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/espaguete.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Lasanha a Bolonhesa', 49.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Camadas intercaladas da nossa deliciosa massa caseira, com molho bolonhesa e molho bechamel, presunto e muito queijo derretido.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/lasanha.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Nhoque ao 4 queijos', 59.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Massa fresca de nhoque, ao molho de bechamel com uma seleção exclusiva de queijos regionais.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/nhoque.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Conchiglione', 39.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Massa fresca recheado com a mais saborosa carne, acompanhado com o molho à napolitana feito com tomates organicos, alho, orégano, azeite, manteiga e salsinha.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/conchiglione.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Risoto Funghi', 59.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Risoto Funghi feito com ingredientes finos e o toque especial do chef.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/risoto_funghi.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Risoto de Camarão', 72.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Risoto de camarões selecionados com especiarias típicas e um delicioso molho de acompanhamento.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/risotoCamarao.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Risoto de Alho poró', 52.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Risoto de alho poro feito com ingredientes frescos e selecionados com o toque especial de limão.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/risotoAlhoPoro.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Água', 2.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Garrafa de água mineral podendo ser com ou sem gás.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/agua.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Vinho Tinto', 22.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Taça do melhor vinho tinto da casa', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/vinhoTinto.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Vinho Branco', 20.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Taça do melhor vinho branco da casa', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/vinhobranco.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Refrigerante', 6.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Refrigerante em lata, podendo ser coca-cola, sprit, ou kuat.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/refri.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Suco Natural', 9.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Suco natural de frutas da estação.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/suco.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Tiramissu', 26.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Nossa deliciosa receita tradicional, leva camadas de biscoitos champagne embebidos no café da casa, e camadas de queijo mascarpone cobertos com uma fina camada de cacau em pó.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/tiramissu.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Cannoli', 34.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Nossa massa leve e crocante, em opção com recheio tradicional de creme de ricota e pistache ou nutella. Contém 2 unidades.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/canolli.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Panna Cotta', 26.9, TIMESTAMP WITH TIME ZONE '2022-07-13T20:50:07.12345Z', 'Nossa típica sobremesa Piemontese a base de creme de leite fresco, com morangos e redução de balsâmico.', 'https://github.com/greicyitakura/mangiaBene/blob/main/pitII/imagens/pannaCota.jpg');


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 5);